# HUCKEL Molecular Orbital (HMO) Calculations

CHEM344  Physical Chemistry \
Department of Chemistry \
Illinois Institute of Technology \



Original Bash Code By Jingbai Li \
Translated to Python by Joseph DePaolo-Boisvert \
HUCKELMO Version 2.0  Aug 30th 2017 \
Written Nov 2022; Last Updated Nov 2024



### Basic Operations in Python
Python can be used to perform basic mathematical operations.

In [1]:
#Addition
1 + 1

2

In [ ]:
#Subtraction
10 - 8

2

In [ ]:
#Multiplication
13 * 5.1

66.3

In [ ]:
#Division
print(77 / 10) #Float Division
print(77 // 10) #Integer Division

7.7
7


In [ ]:
#Exponentiation
5**3

125

In [ ]:
#Modulus (Remainder of Division)
14 % 5

4

### Variables and DataTypes
Numbers (and other types of data) can be stored in user-defined **variables**.\
A vairable is assigned to data using a single equals sign (=).

In [ ]:
#Strings
my_string = 'A string is a series of characters'
print(my_string)

A string is a series of characters


A double equals sign (==) will check if the two sets of data on either side are equal, returning True if they are, and False if they are not.\
The values True and False are called **Booleans**.

In [ ]:
#Booleans (True or False values)
my_first_bool = 1 == 2
my_second_bool = 1/2 == 0.5
print(my_first_bool, my_second_bool)

False True


Lists are collections of data, they don't have to be the same type of data!

In [ ]:
#Lists (A series of data)
my_list = [182.25, 18//3, "A string", 3/2 == 1.5]
my_list_types = [type(element) for element in my_list]
print(my_list)
print(my_list_types)

[182.25, 6, 'A string', True]
[<class 'float'>, <class 'int'>, <class 'str'>, <class 'bool'>]


Notice that the different elements of the list (**expressions**) evaluated to their **return value** in the creation of thelist.\
Different elements of the list can be retrieved by a process called **indexing**.\
Indexing is zero-based meaning that the first value in the list is at index 0, the next at index 1, etc.\
Indexes are always **integers**.\
In the cell below, **assign the appropriate index** to the variable *my_index* so that the cell prints the **string**

In [ ]:
my_index = # INSERT APPRORIATE VALUE #
value = my_list[my_index]
print(value)

A string


Indexing can also be done with **negative integers** which count backward from the end of the list.\
Index -1 is the last element of the list, -2 the second to last, etc.\
In the cell below, **assign a negatively valued index** to *my_index* so that the cell prints the **float**

In [ ]:
my_index = # INSERT APPRORIATE VALUE #
value = my_list[my_index]
print(value)

182.25


### For loops and While loops
**Loops** will iterate over a collection of values, such as a list. \
A **For Loop** will iterate a value over a predefined set.

In [ ]:
print(my_list)
for element in my_list:
    print(element)

[182.25, 6, 'A string', True]
182.25
6
A string
True


In the cell below, write your own **For loop** which iterates over the given list of **integers**. \
Within the loop, square each value, and then print the result.

In [ ]:
given_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
# Write a FOR loop of your own #

1
2
3
4
5
6
7
8
9


A **While Loop** will continue to interate until the Boolean condition defining the loop evaluates to **False**

In [ ]:
i = 1
while i <= 10:
    print(i)
    i = i + 1

1
2
3
4
5
6
7
8
9
10


In the cell below, write your own **While loop**. \
From an an initial value *i*, square the value, print the result, and increase the value of *i* by one. \
Continue to iterate the loop until the squared value of *i* is greater than 50. \
If done correctly, only values below 50 should be printed. \
An initial value of the iterable *i* is provided.

In [ ]:
# Write a WHILE loop of your own #

0
1
4
9
16
25
36
49


### Functions
A **function** is a predifined code that will execute the code within the function. \
A function takes one or more **arguments** and evaluates to it's **return value**. \
Below is an example of a function which takes as input two arguments. \
The function will multiply the first argument by 3, take the square root, and get the modulus against the second argument.

In [ ]:
def example_1(foo, bar):
    value = foo*3
    value = value**(1/2)
    value = value % bar
    return value

Notice that the above cell produces no output.  This is because it is the definition of a function, but the function must be **called**.

In [ ]:
my_value = example_1(27, 5)
print(my_value)

4.0


Use the cell below to **write your own function**, which takes 3 arguments as input.
The function should raise the first argument to the power of the second argument, and divide the resulting value by the third argument.

In [ ]:
# Write your own FUNCTION #

In [ ]:
# Call your own FUNCTION #

144938.45454545456


A **lambda function** is a shorthand function useful for mathematical operations. \
The lambda function below will take two arguments, multiplying the first by two and dividing by the second.

In [2]:
lam_fun = lambda x, y : (2*x)/y

In [3]:
z = lam_fun(15, 3)
print(z)

10.0


### Packages
Python **packages (modules)** are collections of code that have additional functionality.\
The power of python lies in the ability to create, distribute, and **import** modules.

In [4]:
import numpy as np
from numpy import real
import glob
import math
import matplotlib.pyplot as plt
%matplotlib inline

Some Example Calculations using numpy arrays

In [5]:
a = np.arange(1,9)
b = np.arange(15,23)
print(a,b)

[1 2 3 4 5 6 7 8] [15 16 17 18 19 20 21 22]


In [6]:
#Vector Operations
print(a+b)
print(b-a)
print(a*b)
print(b/a)

[16 18 20 22 24 26 28 30]
[14 14 14 14 14 14 14 14]
[ 15  32  51  72  95 120 147 176]
[15.          8.          5.66666667  4.5         3.8         3.33333333
  3.          2.75      ]


In [7]:
a, b = a.reshape((2,4)), b.reshape((2, 4))
print(a)
print(b)
#Try running the cell above

[[1 2 3 4]
 [5 6 7 8]]
[[15 16 17 18]
 [19 20 21 22]]


In [8]:
print(a+b)

[[16 18 20 22]
 [24 26 28 30]]


## Molecular Orbitals Calculation

In this laboratory, you will handcraft the Huckel Matrices for Benzene as well as all of the dyes from the conjugated Dyes Lab. \\
From these Huckel matrices, the Huckel MO energy levels will be calculated, as well the atomic orbitals' coefficeints (contributing to each Huckel MO). \\
Together, we will work through building this matrix for Benzene, and getting the output.  One of the dyes is constructed already as an example for you to follow while doing the other five. \\
As a final result for this laboratory, demonstrate the calculation of the Huckel matrices for all dyes, get the Huckel MO levels, report the HOMO-LUMO gap in units of beta as well as in units of wavelength (nm), and calculate the delocalization energy.

In [9]:
def make_H_matrix_for_benzene(a, b):
    h_matrix = np.array([[0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0]])
    return h_matrix

def get_eigs(h_matrix):
    eig_vals, eig_vecs = np.linalg.eig(h_matrix)
    #eig_inv_vecs = np.linalg.inv(eig_vecs)
    return eig_vals, eig_vecs

In [10]:
benzene_h_matrix = make_H_matrix_for_benzene(0, -1)

MO_levels, eigen_vectors = get_eigs(benzene_h_matrix)

In [11]:
print(MO_levels)
print(eigen_vectors)

[0. 0. 0. 0. 0. 0.]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [12]:
print(f'MO energies are: \n{np.sort(np.round(MO_levels, 2))}')
sorted_indices = np.argsort(MO_levels)
print(f'eigen column vectors are: \n{np.round(eigen_vectors[:,sorted_indices],2)}')

MO energies are: 
[0. 0. 0. 0. 0. 0.]
eigen column vectors are: 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Calculate the energy levels for pyridine

In [13]:
def make_H_matrix_for_pyridine(a, b, c, d):
    h_matrix = np.array([[0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0]])
    return h_matrix

def get_eigs(h_matrix):
    eig_vals, eig_vecs = np.linalg.eig(h_matrix)
    #eig_inv_vecs = np.linalg.inv(eig_vecs)
    return eig_vals, eig_vecs

In [14]:
pyridine_h_matrix = make_H_matrix_for_pyridine(0, -1, -0.5, -0.8)

MO_levels, eigen_vectors = get_eigs(pyridine_h_matrix)

In [15]:
print(f'MO energies are: \n{np.sort(np.round(MO_levels, 2))}')
sorted_indices = np.argsort(MO_levels)
print(f'eigen column vectors are: \n{np.round(eigen_vectors[:,sorted_indices],2)}')

MO energies are: 
[0. 0. 0. 0. 0. 0.]
eigen column vectors are: 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Now let's calculate energy levels for dye molecules starting with 1,1'-diethyl-4,4'-carbocyanine

In [ ]:
def make_H_matrix_4_4_4carbo(a, b, c, d):
  #                     N  2  3  4  5  6  7  8  9  X   N  2  3  4  5  6  7  8  9  X   A  B  C
  h_matrix = np.array([[c, d, 0, 0, 0, 0, 0, 0, 0, d,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#N
                       [d, a, b, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#2
                       [0, b, a, b, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#3
                       [0, 0, b, a, b, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  b, 0, 0],#4
                       [0, 0, 0, b, a, b, 0, 0, 0, b,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#5
                       [0, 0, 0, 0, b, a, b, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#6
                       [0, 0, 0, 0, 0, b, a, b, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#7
                       [0, 0, 0, 0, 0, 0, b, a, b, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#8
                       [0, 0, 0, 0, 0, 0, 0, b, a, b,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#9
                       [d, 0, 0, 0, b, 0, 0, 0, b, a,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#X

                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  c, d, 0, 0, 0, 0, 0, 0, 0, d,  0, 0, 0],#N
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  d, a, b, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0],#2
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, b, a, b, 0, 0, 0, 0, 0, 0,  0, 0, 0],#3
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, b, a, b, 0, 0, 0, 0, 0,  0, 0, b],#4
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, b, a, b, 0, 0, 0, b,  0, 0, 0],#5
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, b, a, b, 0, 0, 0,  0, 0, 0],#6
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, b, a, b, 0, 0,  0, 0, 0],#7
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, b, a, b, 0,  0, 0, 0],#8
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, b, a, b,  0, 0, 0],#9
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  d, 0, 0, 0, b, 0, 0, 0, b, a,  0, 0, 0],#X

                       [0, 0, 0, b, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  a, b, 0],#A
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  b, a, b],#B
                       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 0, b, 0, 0, 0, 0, 0, 0,  0, b, a]])#C
  return h_matrix



In [ ]:
four_four_carbo_H_matrix = make_H_matrix_4_4_4carbo(0,#alpha param for C
                                                   -1, #beta param for C-c
                                                   -0.5, #alpha param for N
                                                   -0.8)  # beta param for C-N
MO_levels, eigen_vectors = get_eigs(four_four_carbo_H_matrix)

In [ ]:
np.around(MO_levels, decimals=2)

In [ ]:
for i in range(eigen_vectors.shape[0]):
  print(f"The column {i} vector is {np.around(eigen_vectors[:, i], decimals=2)}")

Below this text, as needed, add additional code cells to complete the assignment.  In this text cell, fill in the blank values below for the HOMO-LUMO Gaps and Delocalization Energies:

1-1'-diethyl-2-2'-cyanine: \\
HOMO-LUMO = \\
Delocalization Energy = \\

1-1'-diethyl-2-2'-carbocyanine: \\
HOMO-LUMO = \\
Delocalization Energy = \\

1-1'-diethyl-2-2'-dicarbocyanine: \\
HOMO-LUMO = \\
Delocalization Energy = \\

1-1'-diethyl-4-4'-cyanine: \\
HOMO-LUMO = \\
Delocalization Energy = \\

1-1'-diethyl-4-4'-carbocyanine: \\
HOMO-LUMO = \\
Delocalization Energy = \\

1-1'-diethyl-4-4'-dicarbocyanine: \\
HOMO-LUMO = \\
Delocalization Energy = \\

